ProjectBoss/Controllers/ChoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectBoss.Data;
using ProjectBoss.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;



namespace ProjectBoss.Controllers
{
    public class ChoresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Member> _userManager;

        public ChoresController(ApplicationDbContext context, UserManager<Member> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
	

		// POST: Chores/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[Authorize]
		[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTask([Bind("Id,Body,ProjectId")] Chore chore)
        {
			// check if signed in user is part of ProjectMembers table
			// redirect if user is not found
			var projectMember = await _context.ProjectMember
                .Where(ProjectMember => ProjectMember.ProjectId == chore.ProjectId && ProjectMember.MemberId == _userManager.GetUserId(User))
                .ToListAsync();

            if (projectMember.Count == 0)
            {
                TempData["DisplayMessage"] = "You are not authorize to perform this task.";
				return RedirectToAction("details", "projects", new { id = chore.ProjectId });
            }

            // create a new activity when a chore is created            
			var project = await _context.Project.FindAsync(chore.ProjectId);

			if (ModelState.IsValid)
            {
                var newActivity = new ActivityModel()
                {
					MemberId = _userManager.GetUserId(User),
					ProjectId = project.Id,
					Description = "created_task",
					Subject = chore.Body
			    };

                _context.Add(newActivity);
                _context.Add(chore);
                await _context.SaveChangesAsync();
                return RedirectToAction("details", "projects", new { id = chore.ProjectId});
            }

			return RedirectToAction("details", "projects", new { id = chore.ProjectId });

		}


		// POST: Chores/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[Authorize]
		[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditTask(int id, [Bind("Id,Body,ProjectId, Completed")] Chore chore)
        {

			// check if signed in user is part of ProjectMembers table
			// redirect if user is not found
			var projectMember = await _context.ProjectMember
				.Where(ProjectMember => ProjectMember.ProjectId == chore.ProjectId && ProjectMember.MemberId == _userManager.GetUserId(User))
				.ToListAsync();

			if (projectMember.Count == 0)
			{
				TempData["DisplayMessage"] = "You are not authorize to perform this task.";
				return RedirectToAction("details", "projects", new { id = chore.ProjectId });
			}

			if (id != chore.Id)
            {
				return RedirectToAction("details", "projects", new { id = chore.ProjectId });

			}

			if (ModelState.IsValid)
            {           

			var project = await _context.Project.FindAsync(chore.ProjectId);
                try
                {
					// since we can have multiple users working on the same project,
					// we need to ensure that on post update, the project owners data
					// won't be overridden with the ProjectMembers data.

					// find the project and get its current values.
					var getCreatedDateValuesFromDB = await _context.Chore 
	                    .AsNoTracking()
	                    .FirstOrDefaultAsync(chore => chore.Id == id);

					// keep the created date values the same when updating the row
					// without this statement, the CreatedDate will be set to NOW
					chore.CreatedDate = getCreatedDateValuesFromDB.CreatedDate;

					// create a new activity for each corresponding action
                    if(chore.Completed == true)
                    {
						var newActivity = new ActivityModel()
						{
                            MemberId = _userManager.GetUserId(User),
                            ProjectId = project.Id, 
                            Description = "completed_task", 
                            Subject = chore.Body 
						};
						_context.Update(newActivity);
                    }

					if (chore.Completed == false)
					{
						var newActivity = new ActivityModel()
						{
							MemberId = _userManager.GetUserId(User),
							ProjectId = project.Id,
							Description = "updated_task",
							Subject = chore.Body
						};
						_context.Update(newActivity);
					}

					if (chore.Completed == false && chore.Body == getCreatedDateValuesFromDB.Body)
					{
						var newActivity = new ActivityModel()
						{
							MemberId = _userManager.GetUserId(User),
							ProjectId = project.Id,
							Description = "renewed_task",
							Subject = chore.Body
						};
						_context.Update(newActivity);
					}

					_context.Update(chore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChoreExists(chore.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("details","projects", new { Id = chore.ProjectId });
            }

			return RedirectToAction("details", "projects", new { Id = chore.ProjectId });

		}


		// POST: Chores/Delete/5
		[Authorize]
		[HttpPost, ActionName("DeleteTask")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTask(int id)
        {
			var choreContext = await _context.Chore.FindAsync(id);

			var projectMember = await _context.ProjectMember
				.Where(ProjectMember => ProjectMember.ProjectId == choreContext.ProjectId && ProjectMember.MemberId == _userManager.GetUserId(User))
				.ToListAsync();

			if (projectMember.Count == 0)
			{
				TempData["DisplayMessage"] = "You are not authorize to perform this task.";
				return RedirectToAction("details", "projects", new { id = choreContext.ProjectId });
			}

			if (_context.Chore == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Chores'  is null.");
            }
            var chore = await _context.Chore.FindAsync(id);
            if (chore != null)
            {
                _context.Chore.Remove(chore);
            }


			await _context.SaveChangesAsync();
            return RedirectToAction("details","projects", new { id = choreContext.ProjectId });
        }

        private bool ChoreExists(int id)
        {
          return (_context.Chore?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProjectBoss/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectBoss.Data;
using ProjectBoss.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Collections.Immutable;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Query;



namespace ProjectBoss.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Member> _userManager;

        public ProjectsController(ApplicationDbContext context, UserManager<Member> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Projects
        [Authorize]
        public async Task<IActionResult> Index()
        {

            var applicationDbContext = _context.Project
                .Include(p => p.ProjectMembers)
                .OrderByDescending(p => p.UpdatedDate);	

			return View(await applicationDbContext.ToListAsync());
        }

        // GET: Projects/Details/5
        [Authorize]
		[ActionName("Details")]
		public async Task<IActionResult> ProjectDetails(int? id)
        {
	
			// check if signed in user is part of ProjectMembers table
			// redirect if user is not found
			var projectMember = await _context.ProjectMember
				.Where(p => p.ProjectId == id && p.MemberId == _userManager.GetUserId(User))
				.ToListAsync();

			if (projectMember.Count() == 0)
			{
				return RedirectToAction("index", "projects");
			}


			if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .Include(p => p.Member)
                .Include(p => p.Chores)
                .Include(p => p.Activities)
                .FirstOrDefaultAsync(m => m.Id == id);


            if (project == null)
            {
                return RedirectToAction("index","projects");
            }


			ViewData["MembersList"] = new SelectList(_context.Set<Member>(), "Id", "FirstName");

            return View(project);
        }

        // POST: Projects/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProject([Bind("Id,Title,Description, MemberId, ProjectId")] Project project)
        {
            if (ModelState.IsValid)
            {
                // create a new project
                // create a new activity
                // add project creator to ProjectMembers list 

				_context.Add(project); 
				await _context.SaveChangesAsync(); // project must exist in database or ActivityModel will fail

				var newActivity = new ActivityModel() 
                {
                    ProjectId = project.Id,
                    MemberId = project.MemberId,
                    Description = "created_project",
                    Subject = project.Title
                };
         
                var newProjectMember = new ProjectMember()
                {
                    ProjectId = project.Id,
                    MemberId = project.MemberId,
                };

                _context.Add(newActivity);
                _context.Add(newProjectMember);
				await _context.SaveChangesAsync();

				return RedirectToAction("details","projects",new {id = project.Id});
            }

            return RedirectToAction("index", "projects");
        }

		// GET: Projects/Edit/5
		[Authorize]
		public async Task<IActionResult> Edit(int? id)
        {
            // check if signed in user is part of ProjectMembers table
            // redirect if user is not found
			var projectMember = await _context.ProjectMember
	            .Where(p => p.ProjectId == id && p.MemberId == _userManager.GetUserId(User))
	            .ToListAsync();

			if (projectMember.Count() == 0)
			{
				return RedirectToAction("index", "projects");
			}

			if (id == null || _context.Project == null)
            {
				return RedirectToAction("index", "project");
			}

			var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
				return RedirectToAction("index", "project");
			}

			ViewData["MemberId"] = new SelectList(_context.Users, "Id", "Id", project.MemberId);
            return View(project);
        }
		

		// POST: Projects/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> EditProjectDetails(int id, [Bind("Id,Title,Description,MemberId")] Project project)
		{
			// check if signed in user is part of ProjectMembers table
			// redirect if user is not found
			var projectMember = await _context.ProjectMember
				.Where(p => p.ProjectId == project.Id && p.MemberId == _userManager.GetUserId(User))
				.ToListAsync();

			if (projectMember.Count() == 0)
			{
				TempData["DisplayMessage"] = "You are not authorize to perform this task.";
				return RedirectToAction("index", "project", new { id = project.Id });

			}

			if (id != project.Id)
			{
				return RedirectToAction("index", "project");
			}

			if (ModelState.IsValid)
			{
				try
				{
					// since we can have multiple users working on the same project,
					// we need to ensure that on post update, the project owners data
					// won't be overridden with the ProjectMembers data.

					// find the project and get its current values.
					var getCurrentValueFromDB = await _context.Project
						.AsNoTracking()
						.FirstOrDefaultAsync(p => p.Id == id);
					
					// keep the project owner and the created date values
					// the same when updating the table.
					// without this statement, the ProjectMembers Id
					// will be used and the CreatedDate will be set to NOW
					project.MemberId = getCurrentValueFromDB.MemberId;
					project.CreatedDate = getCurrentValueFromDB.CreatedDate;

					// create an activity when the Project Title will be changed.
					if (project.Title != getCurrentValueFromDB.Title)
					{
						var newActivity = new ActivityModel()
						{
							ProjectId = project.Id,
							MemberId = _userManager.GetUserId(User),
							Description = "updated_title",
							CreatedDate = getCurrentValueFromDB.CreatedDate,
							Subject = $"{getCurrentValueFromDB.Title} <span class='text-black'>to</span> {project.Title}"
						};
					_context.Add(newActivity);

					}

					// create an activity when the Project Description will be changed.
					if (project.Description != getCurrentValueFromDB.Description)
					{
						var newActivity = new ActivityModel()
						{
							ProjectId = project.Id,
							MemberId = _userManager.GetUserId(User),
							Description = "updated_description",
							CreatedDate = getCurrentValueFromDB.CreatedDate,
							Subject = project.Title
						};

					_context.Add(newActivity);
					}

					// record the changes then save to the database.
					_context.Update(project);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ProjectExists(project.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction("details", "projects", new { id = id });
			}
			ViewData["MemberId"] = new SelectList(_context.Users, "Id", "Id", project.MemberId);
			return View(project);
		}

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> UpdateNotes([Bind("Id,Title,Description,MemberId, Notes")] Project project)
        {

			var projectMember = await _context.ProjectMember
				.Where(ProjectMember => ProjectMember.ProjectId == project.Id && ProjectMember.MemberId == _userManager.GetUserId(User))
				.ToListAsync();

			if (projectMember.Count == 0)
			{
				TempData["DisplayMessage"] = "You are not authorize to perform this task.";
				return RedirectToAction("details", "projects", new { id = project.Id });
			}

			var getCurrentValueFromDB = await _context.Project 
	            .AsNoTracking()
	            .FirstOrDefaultAsync(p => p.Id == project.Id);

			if (project.Notes != getCurrentValueFromDB.Notes)
			{
                project.MemberId = getCurrentValueFromDB.MemberId;
                var activity = new ActivityModel();
                activity.MemberId = _userManager.GetUserId(User);
				activity.Description = "updated_notes";
				activity.CreatedDate = getCurrentValueFromDB.CreatedDate;
				activity.Subject = project.Title;
                activity.ProjectId = project.Id;

				_context.Update(project);
                _context.Update(activity);
				await _context.SaveChangesAsync();
			};

			return RedirectToAction("details", "projects", new { id = project.Id });
        }

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AddMember([Bind("Id,Title,MemberId")] Project project)
        {
			var memberExist = await _context.ProjectMember
	            .Where(p => p.ProjectId == project.Id && p.MemberId == project.MemberId)
	            .ToListAsync();

            if(memberExist.Count() == 0)
            {
                var projectMember = new ProjectMember()
                {
                    MemberId = project.MemberId,
                    ProjectId = project.Id
                };
                
			    _context.Add(projectMember);

                var memberActivity = new ActivityModel()
                {

                    ProjectId = project.Id,
                    MemberId = project.MemberId,
                    Description = "added_member",
                    Subject = project.Title
                };

                _context.Activity.Add(memberActivity);

ProjectBoss/Views/Projects/Create.cshtml
@using ProjectBoss.Data;
@using Microsoft.AspNetCore.Identity;
@model ProjectBoss.Models.Project
@inject UserManager<Member> userManager
@inject ApplicationDbContext context
@{
    ViewData["Title"] = "Create";
    
}


<form asp-action="create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="bg-white mt-5 mx-auto w-50 rounded-5 p-5">
        <div class="mx-auto text-center">
            <h2 class="fs-3">Start Something New</h2>
        </div>
        <div class="mb-3">
          <label for="formGroupExampleInput" class="form-label">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
          <label for="formGroupExampleInput2" class="form-label">Description</label>
            <textarea name="Description" class="form-control" rows="10"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <input hidden type="text" name="MemberId" value="@userManager.GetUserId(User)" />
        <div class="mt-4">
            <Button type="submit" class="btn btn-info text-white me-2">Create Project</Button>
            <a asp-action="Index">Cancel</a>
        </div>
    </div>
</form>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectBoss/Views/Projects/Delete.cshtml
@model ProjectBoss.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Member.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectBoss/Views/Projects/Details.cshtml
@using ProjectBoss.Data;
@using Microsoft.AspNetCore.Identity;
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
@model ProjectBoss.Models.Project
@inject UserManager<Member> userManager;
@inject ApplicationDbContext _context;


@{
	
	ViewData["Title"] = "Details";
	string showCheckMark = "checked";
	string disableInputField = "disabled";
	string textStrike = "text-grey text-decoration-line-through";
	
	var displayMessage = "";
	if (TempData.ContainsKey("DisplayMessage"))
	{
		displayMessage = TempData["DisplayMessage"].ToString();
	}


}
						

<div class="row mt-5">
	<div class="MAIN col-lg-9">
		<div class="row">
			<div class="BREADCRUMBS d-md-flex align-items-end mb-2">
				<h2 class="me-auto text-grey fs-6 small"><a href="/projects" class="text-decoration-none text-grey">My Projects</a> / @Model.Title</h2>
				@{
					var memberExist = _context.ProjectMember.Where(p => p.ProjectId == Model.Id && p.MemberId == userManager.GetUserId(User)).FirstOrDefault();
					
				}
				@if (memberExist != null)
				{
				<a class="btn btn-info text-white me-2" href="/projects/edit/@Model.Id">Edit Project</a>					
				}

				@if(Model.MemberId == userManager.GetUserId(User))
				{
					<!-- Button trigger modal -->
					<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
						Delete Project
					</button>

					<!-- Modal -->
					<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header border-0">
									<h1 class="modal-title fs-5" id="staticBackdropLabel">Confirm Delete</h1>
								</div>
								<div class="modal-body border-0">
									Are you sure you want to delete this project?
							
								</div>
								<div class="modal-footer border-0">
									<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
									<form asp-controller="projects" asp-action="Delete">
										<input type="hidden" name="id" value="@Model.Id" />
										<input type="hidden" name="MemberId" value="@Model.MemberId" />
										<button type="submit" class="btn btn-danger text-white me-2">Delete Project</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				}
			</div>
			<div class="LEFT-MAIN col-65 mt-3">
			<div class="TASK-LABEL mb-4">
					<h2 class="me-auto text-black opacity-50 text-uppercase fw-bold fs-6">
						Tasks
					</h2>
				</div>
			<!--Create Task Start-->
			<div class="CREATE-TASK p-2 mb-4 bg-white shadow-sm nunito rounded-3">
				<h5 class="text-dark border-start border-3 border-info fs-5 ps-4 details-margin-left">
					<form asp-controller="chores" asp-action="CreateTask">
						<div asp-validation-summary="ModelOnly" class="text-danger"></div>
						<input type="hidden" name="ProjectId" asp-for="@Model.Id" />
						<input class="form-control w-100 border-0" name="Body" placeholder="Add a new task"/>
					</form>
				</h5>
			</div>
			<!--Create Task END -->
				
				@if (!Model.Chores.Any())
				{
					<div class="mb-4">
						<span class="text-warning text-danger">There are currently no tasks.</span>
					</div>
				}
				
				<!-- Task Item START-->
				@foreach (var chore in Model.Chores.OrderByDescending( c => c.CreatedDate).ToList())
				{			
					<div class="TASK-ITEM p-2 mb-4 bg-white shadow-sm nunito rounded-3 d-flex align-items-center">
						<div class="TASK-BODY w-100 me-auto">
							<h5 class="text-dark border-start border-3 border-info fs-5 ps-4 details-margin-left">
								<!-- Task Body START-->
								<form asp-controller="chores" asp-action="EditTask">
									<input type="hidden" name="ProjectId" asp-for="@Model.Id" />
									<input type="hidden" name="Id" asp-for="@chore.Id" />
									<input name="Body" class="form-control w-100 border-0 @if(chore.Completed){ @textStrike }" 
									value="@chore.Body" @if(chore.Completed){ @disableInputField }/>
								</form>

								<!-- Task Body END -->
							</h5>
						</div>
						<div class="CHECKBOX ms-2 form-check">		
						<!-- Check Box START -->
							<form asp-controller="Chores" asp-action="EditTask">
								<input type="hidden" name="Id" value="@chore.Id" />
								<input type="hidden" name="Body" value="@chore.Body" />
								<input type="hidden" name="ProjectId" value="@chore.ProjectId" />
								<input name="Completed" class="form-check-input"
								type="checkbox" value="true" onChange="this.form.submit()"
								@if(chore.Completed) { @showCheckMark }

								/>
							</form>			
							<!-- Check Box END-->
						</div>
						<!-- Delete Icon START -->
							<form asp-controller="Chores" asp-action="DeleteTask">
								<input type="hidden" name="id" value="@chore.Id" />
								<input type="hidden" name="MemberId" value="@userManager.GetUserId(User)" />
								<button type="submit" class="btn me-2 px-0 text-danger">
								<svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
								<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path><path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
								</svg>
								</button>
							</form>
						<!-- Delete Icon END -->


					</div>
				}
				<!-- Task Item END -->
				<div class="NOTES-LABEL mb-4">
					<h2 class="me-auto text-black opacity-50 text-uppercase fw-bold fs-6">
						General Notes
					</h2>
				</div>
				
				<!-- General Notes START-->
				<div class="NOTES-CARD card bg-white border-0 shadow-sm rounded-5 my-3">					
					<div class="card-body text-dark">
				<div class="mb-1">
				<!-- Notes START-->
					<form asp-controller="projects" asp-action="UpdateNotes">
						<div asp-validation-summary="ModelOnly" class="text-danger"></div>
						<input type="hidden" asp-for="Id" />
						<input type="hidden" asp-for="Title" />
						<input type="hidden" asp-for="Description" />
						<input type="hidden" name="MemberId" value="@userManager.GetUserId(User)" />
						<textarea name="Notes" class="form-control border-0" rows="3">@Model.Notes</textarea>
						<button type="submit" class="btn btn-info mt-3 text-white">Save</button>
					</form>
				<!-- Notes END -->
				</div>
					</div>
				</div>
				<!-- General Notes END-->

			</div>
			<div class="PROJ-DETAILS col-lg-4 ms-2">
				<div class="card bg-white border-0 shadow-sm rounded-5 my-3">					
					<div class="card-body text-dark">
						<h5 class="card-title mb-4 py-3 pb-1 ps-3 margin-left nunito border-start border-4 border-info">@Model.Title</h5>
						<p class="card-text px-1 text-grey nunito">
							@Model.Description
						</p>
					</div>
				</div>
				@if (displayMessage != "")
				{
					<div class="alert alert-danger alert-dismissible" role="alert">
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
						@displayMessage
					</div>
				}
				<div class="ADD-PROJECT-MEMBERS">
					@if (Model.MemberId == userManager.GetUserId(User))
					{
						<!--Add Project Member START -->
						<form asp-controller="projects" asp-action="AddMember">
							<div class="ADD-MEMBERS input-group mb-4 nunito rounded-3 w-100">
								<input type="hidden" name="Id" value="@Model.Id" />
								<input type="hidden" name="Title" value="@Model.Title" />
								<select asp-for="MemberId" class="form-select" asp-items="ViewBag.MembersList"></select>
								<Button type="submit" class="btn btn-info text-white">Add</Button>
							</div>
						</form>
						<!--Add Project Member END -->
					}
				</div>

				<div class="PROJECT-MEMBERS-LABEL mb-2">
					<h2 class="me-auto text-black opacity-50 text-uppercase fw-bold fs-6">
						Project Members
					</h2>
				</div>
				<div class="MEMBER-AVATARS mb-2">
					<div class="row">
						@{
							foreach (var memberX in _context.ProjectMember.Where(p => p.ProjectId == Model.Id).ToList())
							{
								foreach (var item in userManager.Users.Where(m => m.Id == memberX.MemberId))
								{
									<div class="REMOVE-MEMBER dropdown col-3">
										<a class="avatar avatar-sm p-0" id="profileDropdown" role="button" data-bs-auto-close="outside" data-bs-display="static" data-bs-toggle="dropdown">
											<img src="~/uploads/avatars/@item.AvatarUrl" class="rounded-circle avatar m-1" />
										</a>

										@if (Model.MemberId == userManager.GetUserId(User))
										{
											<ul class="dropdown-menu resize-dropdown" aria-labelledby="profileDropdown">
												<form asp-controller="projects" asp-action="RemoveMember">
													<input type="hidden" name="MemberId" value="@item.Id" />
													<input type="hidden" name="Id" value="@Model.Id" />
												<li>
													<button class="dropdown-item text-danger small">
														<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
															<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z" />
														</svg> Remove
													</button>
												</li>
												</form>
											</ul>
										}

									</div>
								}




							}
						}
					</div>
				</div>

			
			</div>
		</div>
	</div>
	<div class="SIDEBAR col-lg-3">
			<partial name="_ActivityDetails" />
		</div>
</div>